- hosts: all
  tasks:
    - command: echo 'this is failed test'
      register: result
      # 输出结果中包含 failed 字符串，触发失败操作
      failed_when: "'failed' in result.stdout"
      ignore_errors: True

    # 修改 debug 任务状态为 changed， 默认为 ok
    - debug:
        msg: '修改状态为 change'
      changed_when: "'failed' in result.stdout"

    # 默认 shell 任务状态为 changed
    - shell: echo '不出现 changed 状态'
      changed_when: False
